<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand" href="country.php">Week 9 PHP MySQL</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainnav" aria-controls="mainnav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="mainnav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="country.php">Countries</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
